# Generated by Django 5.2.12 on 2026-03-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('MASTER', 'Master (Legio Access)'), ('ADMIN', 'Administrador (Cliente)'), ('GERENCIA', 'Gerencia (Solo Lectura)')], default='GERENCIA', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('config_modulos', models.JSONField(blank=True, default=dict, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
