# Generated by Django 5.2.12 on 2026-03-26 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('config_modulos', models.JSONField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='role',
        ),
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='GERENCIA', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuenta'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.departamento'),
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('direccion', models.CharField(max_length=255)),
                ('coordenadas', models.CharField(max_length=100)),
                ('mail_notificacion', models.JSONField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locaciones', to='usuarios.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='MotivoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField()),
                ('locaciones_ids', models.JSONField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.plan'),
        ),
        migrations.CreateModel(
            name='RazonVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cuenta')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=255)),
                ('celular_contacto', models.CharField(max_length=20)),
                ('correo_contacto', models.EmailField(max_length=255)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('estado_invitacion', models.CharField(max_length=255)),
                ('cedula', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_rostro_url', models.URLField(blank=True, max_length=255, null=True)),
                ('tipo_ingreso', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_vehiculo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('equipo', models.BooleanField(default=False)),
                ('foto_equipo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('documentos', models.BooleanField(default=False)),
                ('documentos_zip', models.URLField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cuenta')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.departamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.locacion')),
                ('motivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.motivovisita')),
                ('tipo_invitacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tipoinvitacion')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.vehiculo')),
            ],
        ),
    ]
